### ISSUE TITLE
编译不通过，有劳帮忙看一下可以吗

### ISSUE THREAD

**Issue by 0819gh** [hanpfei/chromium-net-independent#2]
target_os = "android"
target_cpu = "arm"  # (default)
is_debug = false  # (default)

# Other args you may want to set:
is_component_build = true
is_clang = false
symbol_level = 1  # Faster build with fewer symbols. -g1 rather than -g2
enable_incremental_javac = false # Much faster; experimental
android_ndk_root = "/usr/local/gh/depot_tools/android-ndk-r10e"
android_sdk_root = "/usr/local/gh/depot_tools/android-sdk"
android_sdk_build_tools_version = "23.0.2"

disable_file_support = true
disable_ftp_support = true
enable_websockets = false

use_platform_icu_alternatives = true

gn gen out/Default 报错

ERROR at //build/config/android/rules.gni:2619:9: Script returned non-zero exit code.
        exec_script("//build/android/gyp/aar.py",
        ^----------
Current dir: /usr/local/gh/chromium-net1/out/Default/
Command: python -- /usr/local/gh/chromium-net1/build/android/gyp/aar.py --input-file ../../third_party/android_tools/sdk/extras/android/m2repository/com/android/support/design/24.1.1/design-24.1.1.aar --list
Returned 1.
stderr:

Traceback (most recent call last):
  File "/usr/local/gh/chromium-net1/build/android/gyp/aar.py", line 15, in <module>
    from util import build_utils
  File "/usr/local/gh/chromium-net1/build/android/gyp/util/build_utils.py", line 24, in <module>
    from pylib.constants import host_paths
  File "/usr/local/gh/chromium-net1/build/android/gyp/util/../../pylib/constants/__init__.py", line 17, in <module>
    import devil.android.sdk.keyevent
ImportError: No module named devil.android.sdk.keyevent

See //third_party/android_tools/BUILD.gn:46:1: whence it was called.
android_aar_prebuilt("android_support_design_java") {
^----------------------------------------------------
See //build/config/android/internal_rules.gni:140:23: which caused the file to be included.
            deps += [ "${_target_label}__build_config" ]

**Comment by 0819gh** [comment]
有时候 还是这个错误
root@iZt4ni9a4lel5nj6dbs4wpZ:/usr/local/gh/chromium-net-independent# gn gen out/Default/
ERROR at //build/config/linux/pkg_config.gni:85:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /usr/local/gh/chromium-net-independent/out/Default/
Command: python -- /usr/local/gh/chromium-net-independent/build/config/linux/pkg-config.py -s /usr/local/gh/chromium-net-independent/build/linux/debian_wheezy_i386-sysroot -a x86 glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/usr/local/gh/chromium-net-independent/build/config/linux/pkg-config.py", line 219, in <module>
    sys.exit(main())
  File "/usr/local/gh/chromium-net-independent/build/config/linux/pkg-config.py", line 138, in main
    prefix = GetPkgConfigPrefixToStrip(args)
  File "/usr/local/gh/chromium-net-independent/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/BUILD.gn:88:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //BUILD.gn:301:7: which caused the file to be included.
      "//build/config/linux(//build/toolchain/linux:clang_x86)",
      ^--------------------------------------------------------

**Comment by carl1990** [comment]
遇到同样的错误 感觉就是 Android SDK 相关库没下下来
